### ISSUE TITLE
Only few account fields available through API

### ISSUE THREAD

**Issue by wimg** [orocrm/crm#180]
When I make a request through the REST API for a contact, I get a lot of fields. When I do the same for  an account, I get only the name, createdAt, updatedAt and a few linked entities.
The description field is missing, as well as a custom field we added.

Is there a way to retrieve this as well through the API ?

**Comment by artml** [comment]
@wimg I am not sure about the REST API. But we are actively developing the new JSON-based automated API where all the fields will be available out of the box.

My advice is to try the new API instead of the old REST. It has already been added to master so you can check it on the current dev build.

I'll also ask @vsoroka to provide additional details on the REST API just in case.

**Comment by wimg** [comment]
Using the new API sounds nice, but as far as I can tell it's not complete yet (only GET available) ? And since this is supposed to be used in production, I'd rather not go for a dev build.

It seems odd that even the 'description' field is missing from the query.

**Comment by artml** [comment]
@wimg we have added GET in the past release, but all methods will be shipped in 1.10.

**Comment by wimg** [comment]
By past release you mean 1.9 ? The API won't give me anything more than a few id fields, but no custom fields and no description from the account.

**Comment by wimg** [comment]
BTW : it's not just a problem in accounts. When I add custom fields to the contacts, I have the same issue.

**Comment by artml** [comment]
@wimg yep, these were the limitations of our old API. Account description is a custom field too, and all these fields must have been added manually. Looks like they were not.

Issues like that is one of the main reasons we're developing the completely new and automated API. And frankly I don't think the issue with account fields availability over the old API can be fixed quickly—what you need to do is write API methods for all these fields manually. Should you do it or not mostly depends on how urgent and critical is this issue for your production application.

I am sorry you had this experience with our API. The fix is long due, and will arrive soon.

**Comment by wimg** [comment]
How much of the new API is ready for use ? For now we only need GET.

**Comment by artml** [comment]
@wimg GET should work fine on the current master. But in 1.9 version it was pretty rudimentary and undocumented, so it's hard to tell if your cases will work.

Please check the [current documentation](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/ApiBundle/Resources/doc/index.md) on the new API to get more idea on what's possible.

**Comment by artml** [comment]
@wimg we have released a [blog post on our new API](https://www.orocrm.com/blog/product-updates/new-oro-web-api-now-available) recently, maybe it will help too.
