### ISSUE TITLE
Remove TaskBundle links to sales and magento

### ISSUE THREAD

**Issue by sbani** [orocrm/crm#211]
Hi,

like in `1.9.x` a Bundle links to Bundles you should be able to deactivate.
TaskBundle links to Sales and Magento Bundle which is deactivated in our AppBundle because we don't need it.

The Problem exists in `Oro\CRMTaskBundle\Migrations\Schema\OroCRMTaskBundleInstaller`:

> ```
> ERROR: There is no table with name 'db.orocrm_sales_lead' in the schema.
> ```

The problem is here: 
https://github.com/orocrm/crm/blob/master/src/Oro/CRMTaskBundle/Migrations/Schema/v1_0/OroCRMTaskBundle.php#L44-L52

You should first check if the bundles are in use (or simpler: if the table exists).

Regards

**Comment by sbani** [comment]
Hi @artml: When is `2.0` ready for release? Because I think it's a bigger bug if you cannot install the application...

**Comment by artml** [comment]
@sbani we are currently targeting late autumn.

**Comment by mbessolov** [comment]
@sbani OroCRM application is meant to work in its integral entirety. Ripping it apart will unequivocally cause bugs.

By removing some of OroCRM bundles you've broken the OroCRM application integrity, which OroCRMTaskBridgeBundle depends upon. The proposed workaround, even though it may suite your current needs, just aggravates the integrity breach even further. For example let's take a look what will happen if in a few months you decide to add the Sales bundle back. As you may imagine, because the v1_0 migration has already been executed before, the association between tasks and oro_sales_* tables will not be created. Which will require another workaround to fix this newly created problem.

Instead of trying to incorporate workarounds into OroCRMTaskBridgeBundle you may consider removing it as well and creating your own MyApplicationTaskBridgeBundle with the migrations that will create associations only to the tables that you have not removed from OroCRM application.

**Comment by mbessolov** [comment]
In order to address the bundle dependencies in the product properly, as Symfony doesn't provide any tools to do it simply, we would have to create individual bridge bundles for every case:
- CRMAccountTaskBridgeBundle
- CRMSalesTaskBridgeBundle
- CRMMagentoTaskBridgeBundle
- ...
and similar bridges for the CallBundle, and then for each other bundle that somebody may decide to removed from the OroCRM application, which will quickly become unmanageable.

In the next release of OroCommerce we are adding a simpler option - feature toggles. A feature toggle will allow to disable a feature (everything included in the feature definition - all its UI functionality, routes, APIs, workflows, etc.) through configuration without removing the actual code. If you are interested please check the OroCommerce Beta 4 release in a few weeks. Feature toggles will become available in subsequent OroPlatform and OroCRM releases and we will be open for feature definition contributions.

**Comment by mkudelya** [comment]
For now, [TaskBundle](https://github.com/orocrm/OroCRMTaskBundle) is extracted from CRM. I'm closing the issue.
