### ISSUE TITLE
Remove OroCRMCallBridgeBundle links to other bundles

### ISSUE THREAD

**Issue by sbani** [orocrm/crm#213]
Basically the same problem like #211.
I will create a PR.

Please test these cases in unit/functional tests.

The problem is here: 
https://github.com/orocrm/crm/blob/master/src/Oro/CRMCallBridgeBundle/Migrations/Schema/v1_0/OroCRMCallBridgeBundle.php#L36-L45

Regards

**Comment by artml** [comment]
Hi @sbani 

thank you very much for your contribution. We will review your PR and will merge it shortly.

**Comment by mbessolov** [comment]
Same as in #212  - OroCRM application is meant to work in its integral entirety. Ripping it apart will unequivocally cause bugs. Instead of trying to incorporate workarounds into OroCRMCallBridgeBundle you may consider removing it as well and creating your own MyApplicationCallBridgeBundle with the migrations that will create associations only to the tables that you have not removed from OroCRM application.

**Comment by mbessolov** [comment]
The solution cannot be accepted as is. Please feel free to reopen if you decide to contribute individual bridges, or wait for the feature toggles to become available .
