### ISSUE TITLE
Create Lead / Opportunity from Contact.

### ISSUE THREAD

**Issue by sadortun** [orocrm/crm#222]
When Viewing a contact. We should have an action to `Create Lead` and `Create Opportunity` directly in the list of actions.

![image](https://cloud.githubusercontent.com/assets/794449/18936864/27f80d56-85b9-11e6-996a-9709d7179754.png)

All the matching fields should be filled by the system before displaying the form to the user.

Have a good day,
Samuel

**Comment by mkudelya** [comment]
Hi @sadortun 

As i know this list of entities contains only activity entities.

**Comment by mbessolov** [comment]
@sadortun we are going to add new configuration options to workflow start transitions that will allow to specify on what other pages the transition button should be visible (in addition to the workflow's related entity view page).

For example, if you have a workflow for working with leads and opportunities, you will also be able to specify that its start transition(s) button(s) should additionally be displayed on contact page, or account page, etc. And you will also be able configure mapping for the new entity creation (so that the fields do not necessarily have to be an exact match in order to be filled automatically).

**Comment by sadortun** [comment]
Hi @mbessolov  @mkudelya 

@mkudelya Yes, you are right. I was suggesting this menu to avoid cluttering the UI. 

@mbessolov Will you offer this as a default option ? I think it would save time to many users to have this.

Thanks,
Samuel

**Comment by artml** [comment]
@sadortun in OroCRM we are going to enable this by default for Account, Contact, and all sorts of Customer entities.

**Comment by sadortun** [comment]
Hi @artml Great to hear it! Will it be added in the next(s) releases ? (you have both, `scheduled for implementation` and `open for contribution` tags 😄

**Comment by artml** [comment]
Partially implemented in 2.0 release – only for opportunities and only from Account/Customer views.

**Comment by sadortun** [comment]
Hi @artml thanks for the update !

Do you think we could also add it for the Contact ?
