### ISSUE TITLE
Opportunities 2.0: /opportunity doesn't load because of JS error

### ISSUE THREAD

**Issue by leomasri** [orocrm/crm#241]
Thanks @mkudelya for your help.

I've given up and started from scratch with a new 1.12 installation. I've managed to successfully upgrade it to 2.0 . However, after enabling Leads and Opportunities, I've getting a js error when trying to access /opportunity

I've tried clearing the cache and also running ```oro:requirejs:build```but couldn't fix it.

Anybody ran into this?

Thanks!

![2017-01-27-162242_1366x768_scrot](https://cloud.githubusercontent.com/assets/5690956/22384545/98bfadf2-e4ad-11e6-8cbd-a87335b70f2e.png)

```javascript
Uncaught TypeError: 'optionValues' must be of type {Array.<Array>|Array.<{name: string, values: Array.<Array>}>}
    at constructor.render (oro.min.js?version=0c729ca6:1527)
    at constructor.render (oro.min.js?version=0c729ca6:1529)
    at R.n.n.exports.t.renderItem (oro.min.js?version=0c729ca6:1488)
    at R.n.n.exports.t.renderAllItems (oro.min.js?version=0c729ca6:1488)
    at R.n.renderAllItems (oro.min.js?version=0c729ca6:1528)
    at R.n.renderAllItems (oro.min.js?version=0c729ca6:1488)
    at R.n.n.exports.t.render (oro.min.js?version=0c729ca6:1488)
    at R.n.render (oro.min.js?version=0c729ca6:1528)
    at R.n.render (oro.min.js?version=0c729ca6:1488)
    at R.n.n.exports.t.renderItem (oro.min.js?version=0c729ca6:1488)
```

Also tried setting require js optimization flag to none in config.yml as per orocrm/platform#110 and rebuild, but it didn't work either :(

**Comment by Grygir** [comment]
Hi @leomasri,

The error that you get is thrown by `Backgrid.SelectCell` https://github.com/cloudflare/backgrid/blob/0.3.7/lib/backgrid.js#L1646 in `render` method. When a result of `this.optionValue` is neither an Array nor an Object.

We have two own extends of `Backgrid.SelectCell`:
- `SelectCell` https://github.com/orocrm/platform/blob/2.0.1/src/Oro/Bundle/DataGridBundle/Resources/public/js/datagrid/cell/select-cell.js#L31-L39, where default `optionValues` is an empty array and actual `optionValues` come from `options.column.get('metadata').choices`. Check what you get as choices list.
- `MultiSelectCell` https://github.com/orocrm/platform/blob/2.0.1/src/Oro/Bundle/DataGridBundle/Resources/public/js/datagrid/cell/multi-select-cell.js#L43-L78, where render method is completely overloaded

Regarding:

> Also tried setting require js optimization flag to none in config.yml as per orocrm/platform#110 and rebuild, but it didn't work either :(

Just have checked, updated  `app/config/config.yml`
```yml
oro_require_js:
   # ...
    build:
        optimize: "none"
```
and ran `app/console oro:requirejs:build`, and `oro.min.js` was not modified

To find what the problem is, I would recommend:
1. To rename `oro.min.js` to e.g. `oro_origin.min.js`
1. Add debug code in to https://github.com/orocrm/platform/blob/2.0.1/src/Oro/Bundle/DataGridBundle/Resources/public/js/datagrid/cell/select-cell.js#L32 to see what invalid `choices` you get and what column it is.
1. And run application without js-build file, application will use source files.

**Comment by leomasri** [comment]
Thanks @Grygir !

I've moved on and restarted with a fresh installation from scratch. Everything's working fine now.

Thanks again,
