### ISSUE TITLE
How to hide dynamic column from datagrid?

### ISSUE THREAD

**Issue by kusgpt26** [orocrm/crm#279]
I have an installation of OROCRM 2.0. I have created an entity Asset than mapped asset with Account Bundle with migration.

```
class AccountMaptoAsset implements Migration, ExtendExtensionAwareInterface
{
  protected $extendExtension;

  public function setExtendExtension(ExtendExtension $extendExtension)
  {
      $this->extendExtension = $extendExtension;
  }

  public function up(Schema $schema, QueryBag $queries)
  {
      $this->extendExtension->addManyToOneRelation(
          $schema,
          'custom_asset', // owning side table
          'account', // owning side field name
          'orocrm_account', // inverse side table
          'name', // column name is used to show related entity
          ['extend' => ['owner' => ExtendScope::OWNER_CUSTOM]]
      );
      $this->extendExtension->addManyToOneInverseRelation(
          $schema,
          'custom_asset', // owning side table
          'account', // owning side field name
          'orocrm_account', // inverse side table
          'assets', // inverse side field name
          ['name'], // column names are used to show a title of owning side entity
          ['name'], // column names are used to show detailed info about owning side entity
          ['name'], // Column names are used to show owning side entity in a grid
          ['extend' => ['owner' => ExtendScope::OWNER_CUSTOM]]
      );
  }
}

```
All things working properly and in datagrid a column named ACCOUNT automatic appears according to migration.

But i want to hide or remove this column ACCOUNT from my datagrid. I don't understand how to do this beacuse in datagrids.yml file i have not written any line of code to show this column.

Is there are any way to handle this? Please Reply if any possibility to do this.

**Comment by d-beekeeper** [comment]
Hi, kusgpt26
Yes, you can achieve this using datagrid event listeners.
You need to create your own listener for your datagrid and add option "'renderable' => false" to column 'ACCOUNT'
Please take a look at this example:
https://github.com/orocommerce/orocommerce/blob/master/src/Oro/Bundle/TaxBundle/EventListener/CustomerTaxCodeGridListener.php#L16
Although, it is from orocommerce, in this case it doesnt matter.

**Comment by alex-n-2k7** [comment]
Hi @kusgpt26 
This issue is related to #282.
There are two ways to hide column from datagrid:

1. the 1st one is via UI:
- goto "System" -> "Entities" -> "Entity Management"
- find your entity "Asset", and click "View" action -> you will see the grid with fields
- find the field you want to hide from grid and click "Edit" action
- in "Other" section find the option "Add to Grid Settings" and choose "No"
- "Save" changes

that's all, now the column will not be visible on grid
please pay attention to the similar options "Show on Form" and "Show on View" in case you will need to hide field on Edit or View pages.

For more details, take a look into documentation - https://www.orocrm.com/documentation/current/admin-guide/entities/entity-field-properties#advanced-entity-field-properties

2. the 2nd one, is to preconfigure the field in migration:
- in "$this->extendExtension->addManyToOneRelation" method, the parameter "$options" takes configuration of the field, so you can specify visibility for datagrid, form, view

```
$this->extendExtension->addManyToOneRelation(
    $schema,
    'custom_asset', // owning side table
    'account', // owning side field name
    'orocrm_account', // inverse side table
    'name', // column name is used to show related entity
     [
        'extend' => ['owner' => ExtendScope::OWNER_CUSTOM],
        'form' => ['is_enabled' => false],     // by default, 'true'
        'datagrid' => [
           'is_visible' => DatagridScope::IS_VISIBLE_FALSE // by default, 'IS_VISIBLE_TRUE'
        ],
        'view' => ['is_displayable' => false], // by default, 'true'
     ]
);
```
and the same way for "$this->extendExtension->addManyToOneInverseRelation"

Also, as an example, see https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/WorkflowBundle/Migrations/Schema/OroWorkflowBundleInstaller.php#L529

**Comment by aivus** [comment]
Hi @kusgpt26
Are you still experiencing this issue?
Or it was solved as you mentioned in https://github.com/orocrm/crm/issues/282?

**Comment by kusgpt26** [comment]
Hi @aivus 
Yes i solved this issue. Now you can close this one also.
Thank you!
